CREATE TABLE player_ad_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    player_id BIGINT UNSIGNED NOT NULL,
    placement VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    ad_format VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'rewarded',
    business_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'created',
    expires_at DATETIME(6) NOT NULL,
    claim_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    claimed_at DATETIME(6) NULL,
    claim_result JSON NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ad_session_id (session_id),
    UNIQUE KEY uk_ad_business_reward (player_id, placement, business_key),
    UNIQUE KEY uk_ad_claim_request (player_id, claim_request_id),
    KEY idx_ad_session_player_state (player_id, state, expires_at),
    CONSTRAINT fk_ad_session_player FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_ad_session_placement CHECK (placement IN ('hint','shuffle','auto_remove','level_complete','daily_gift')),
    CONSTRAINT chk_ad_session_format CHECK (ad_format = 'rewarded'),
    CONSTRAINT chk_ad_session_state CHECK (state IN ('created','claimed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务端签发的一次性激励广告奖励会话';
