CREATE TABLE analytics_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    player_id BIGINT UNSIGNED NOT NULL,
    event_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_name VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_time DATETIME(6) NOT NULL COMMENT '客户端时间，仅用于排查',
    received_at DATETIME(6) NOT NULL COMMENT '服务端统计时间',
    app_id INT UNSIGNED NOT NULL DEFAULT 1,
    sdk_type INT NOT NULL DEFAULT 0 COMMENT '0 Web/测试，1000 TikTok',
    channel INT NOT NULL DEFAULT 0,
    game_session_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    level INT UNSIGNED NULL,
    duration_seconds INT UNSIGNED NULL,
    theme_id TINYINT UNSIGNED NULL,
    prop_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_analytics_event (player_id, event_id),
    KEY idx_analytics_events_received (app_id, sdk_type, channel, received_at),
    KEY idx_analytics_events_player (player_id, received_at),
    CONSTRAINT fk_analytics_event_player FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_analytics_event_level CHECK (level IS NULL OR level <= 999),
    CONSTRAINT chk_analytics_event_theme CHECK (theme_id IS NULL OR theme_id <= 58),
    CONSTRAINT chk_analytics_event_prop CHECK (prop_type IS NULL OR prop_type IN ('hint','shuffle','remove'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='无广告版原始幂等统计事件';
