CREATE TABLE player_saves (
    player_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家',
    revision BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
    level INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '零基主线进度，0 表示第 1 关',
    selected_theme TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前使用主题 0..58',
    collecting_theme TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '当前普通主题收集目标',
    coins BIGINT UNSIGNED NOT NULL DEFAULT 0,
    hint_count INT UNSIGNED NOT NULL DEFAULT 3,
    shuffle_count INT UNSIGNED NOT NULL DEFAULT 3,
    remove_count INT UNSIGNED NOT NULL DEFAULT 3,
    sound_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '兼容旧客户端的总声音开关',
    music_enabled TINYINT(1) NOT NULL DEFAULT 1,
    effects_enabled TINYINT(1) NOT NULL DEFAULT 1,
    vibration_enabled TINYINT(1) NOT NULL DEFAULT 1,
    tutorial_completed TINYINT(1) NOT NULL DEFAULT 0,
    client_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (player_id),
    CONSTRAINT fk_player_saves_player FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_player_saves_revision CHECK (revision >= 1),
    CONSTRAINT chk_player_saves_level CHECK (level <= 999),
    CONSTRAINT chk_player_saves_selected_theme CHECK (selected_theme <= 58),
    CONSTRAINT chk_player_saves_collecting_theme CHECK (collecting_theme <= 58),
    CONSTRAINT chk_player_saves_coins CHECK (coins <= 2147483647),
    CONSTRAINT chk_player_saves_hint CHECK (hint_count <= 2147483647),
    CONSTRAINT chk_player_saves_shuffle CHECK (shuffle_count <= 2147483647),
    CONSTRAINT chk_player_saves_remove CHECK (remove_count <= 2147483647),
    CONSTRAINT chk_player_saves_bools CHECK (sound_enabled IN (0,1) AND music_enabled IN (0,1) AND effects_enabled IN (0,1) AND vibration_enabled IN (0,1) AND tutorial_completed IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LinkGame 玩家云存档';
