CREATE TABLE player_daily_gifts (
    player_id BIGINT UNSIGNED NOT NULL,
    day_key DATE NOT NULL COMMENT 'Asia/Tokyo 自然日',
    offer_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'available',
    prop_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'shuffle',
    prop_quantity INT UNSIGNED NOT NULL DEFAULT 1,
    theme_id TINYINT UNSIGNED NULL,
    fragment_index TINYINT UNSIGNED NULL,
    claim_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    claimed_at DATETIME(6) NULL,
    claim_result JSON NULL COMMENT '首次成功领取结果，用于幂等重放',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (player_id, day_key),
    UNIQUE KEY uk_daily_gift_offer (offer_id),
    UNIQUE KEY uk_daily_gift_claim_request (player_id, claim_request_id),
    KEY idx_daily_gift_day_state (day_key, state),
    CONSTRAINT fk_daily_gift_player FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_daily_gift_state CHECK (state IN ('available','claimed')),
    CONSTRAINT chk_daily_gift_prop CHECK (prop_type = 'shuffle' AND prop_quantity = 1),
    CONSTRAINT chk_daily_gift_theme_pair CHECK ((theme_id IS NULL AND fragment_index IS NULL) OR (theme_id IS NOT NULL AND fragment_index IS NOT NULL)),
    CONSTRAINT chk_daily_gift_theme CHECK (theme_id IS NULL OR theme_id IN (7,13,17,20,25,28,31,32,36,37,43,47,50,53,56,57,58)),
    CONSTRAINT chk_daily_gift_fragment CHECK (fragment_index IS NULL OR fragment_index <= 33)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日普通礼包；当前无广告版本不包含双倍奖励字段';
