CREATE TABLE startup_diagnostic_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL,
  launch_id VARCHAR(64) NOT NULL,
  stage VARCHAR(32) NOT NULL,
  event_time DATETIME(3) NOT NULL,
  received_at DATETIME(3) NOT NULL,
  app_id INT NOT NULL,
  sdk_type INT NOT NULL,
  channel INT NOT NULL,
  client_version VARCHAR(32) NOT NULL,
  platform VARCHAR(16) NOT NULL,
  os VARCHAR(16) NULL,
  system_version VARCHAR(64) NULL,
  tiktok_version VARCHAR(32) NULL,
  sdk_version VARCHAR(32) NULL,
  error_code VARCHAR(64) NULL,
  duration_ms INT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_startup_diagnostic_event_id (event_id),
  KEY idx_startup_diagnostic_received_stage (received_at, stage),
  KEY idx_startup_diagnostic_launch (launch_id),
  KEY idx_startup_diagnostic_dimensions (client_version, os, tiktok_version, sdk_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
