CREATE TABLE daily_challenge_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    player_id BIGINT UNSIGNED NOT NULL,
    day_key DATE NOT NULL,
    challenge_level INT UNSIGNED NOT NULL,
    challenge_index TINYINT UNSIGNED NOT NULL,
    mode VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reward_snapshot JSON NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
    start_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    complete_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    complete_result JSON NULL,
    clear_seconds INT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_daily_challenge_attempt_id (attempt_id),
    KEY idx_daily_challenge_level (player_id, challenge_level),
    UNIQUE KEY uk_daily_challenge_start_request (player_id, start_request_id),
    UNIQUE KEY uk_daily_challenge_complete_request (player_id, complete_request_id),
    KEY idx_daily_challenge_attempt_day (player_id, day_key, status),
    CONSTRAINT fk_daily_challenge_attempt_player FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_daily_challenge_index CHECK (challenge_index <= 33),
    CONSTRAINT chk_daily_challenge_mode CHECK (mode IN ('free','replay')),
    CONSTRAINT chk_daily_challenge_attempt_status CHECK (status IN ('active','completed','expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务端生成并固化奖励的每日挑战轮次';
